### ISSUE TITLE
Right clicking signs does nothing in 1.21

### ISSUE THREAD

**Issue by nuttapillar** [md5sha256/AreaShop#30] opened 2024-07-08 14:59 UTC
**Current behavior**
Currently right clicking a rent sign does nothing. Doesn't even open the sign editor. So we have to use the commands to rent/unrent shops.

**Expected behavior**
Right clicking the sign should rent the shop.

**Steps to reproduce**
1. Put the 2.9.1 build of this on a paper 1.21 server
2. Set up shops
3. Right click the rent sign
4. Notice that nothing happens

**Your environment**

* Server platform (Bukkit, Spigot, etc.): Paper
* Server version: 1.21
* AreaShop version: 2.9.1
* WorldEdit version: Bukkit-Official(7.3.4-SNAPSHOT+6815-3adba9f)
* WorldGuard version: Bukkit-Official (7.0.11-beta1+a801a9d)
* Vault version: [1.7.3](url)

**Your config files**

**Comment by md5sha256** [comment] 2024-07-17 09:43
If it isn't even opening up the sign editor then its likely something else which is preventing interaction with signs. The fix for the sign editor will be released in the non-snapshot versions of 2.9.0 and 2.9.1

**Comment by md5sha256** [comment] 2024-07-24 03:56
Ok, the issue is down to the new command syntax changes. I'm not sure why its not logging an error but make sure the sign lines in your profile align with the new command syntax introduce in 2.8+.x 
For example, `/as buy [region]` is now `/as buy [--region <region>]`
I'm going to double check and release 2.9.0 and 2.9.1 with the correct default configs but existing configs will need to be fixed by hand. 
Enabling debug mode may allow you to see if the interaction was processed/command dispatch was attempted.

**Closed as completed by md5sha256** 2024-07-24 03:56 UTC

**Comment by seema84** [comment] 2024-11-26 16:21
This affects more places than just the right click?
This string also does not work with left-click, for example.

        shiftRightClickConsole:
        - 'areashop message %clicker% %lang:confirm-sell|--region %region%|%'

**Comment by nuttapillar** [comment] 2024-11-26 17:49
> Ok, the issue is down to the new command syntax changes. I'm not sure why its not logging an error but make sure the sign lines in your profile align with the new command syntax introduce in 2.8+.x For example, `/as buy [region]` is now `/as buy [--region <region>]` I'm going to double check and release 2.9.0 and 2.9.1 with the correct default configs but existing configs will need to be fixed by hand. Enabling debug mode may allow you to see if the interaction was processed/command dispatch was attempted.

Thanks, but I'm confused, how do I set this up on the sign? I never had to use that command in the past, I'd just do 'as rent' on the first line, region name on the second line, duration on the third line, and price on the 4th. How does the new command fit into this?

**Comment by seema84** [comment] 2024-11-26 17:55
> > Ok, the issue is down to the new command syntax changes. I'm not sure why its not logging an error but make sure the sign lines in your profile align with the new command syntax introduce in 2.8+.x For example, `/as buy [region]` is now `/as buy [--region <region>]` I'm going to double check and release 2.9.0 and 2.9.1 with the correct default configs but existing configs will need to be fixed by hand. Enabling debug mode may allow you to see if the interaction was processed/command dispatch was attempted.
> 
> Thanks, but I'm confused, how do I set this up on the sign? I never had to use that command in the past, I'd just do 'as rent' on the first line, region name on the second line, duration on the third line, and price on the 4th. How does the new command fit into this?

he means in the default.yml these lines

        rightClickPlayer:
        - 'areashop buy --region %region%'

**Comment by md5sha256** [comment] 2024-11-26 18:13
> This affects more places than just the right click? This string also does not work with left-click, for example.
> 
> ```
>     shiftRightClickConsole:
>     - 'areashop message %clicker% %lang:confirm-sell|--region %region%|%'
> ```

anything which runs an areashop command will be affected.

**Comment by seema84** [comment] 2024-11-26 18:17
> anything which runs an areashop command will be affected.

but what do I have to change here, for example?

    shiftRightClickConsole:
    - 'areashop message %clicker% %lang:confirm-sell|--region %region%|%'

this is how it works, but also prints "--region" in the message in the chat

**Comment by md5sha256** [comment] 2024-11-26 18:19
> > anything which runs an areashop command will be affected.
> 
> but what do I have to change here, for example?
> 
> ```
> shiftRightClickConsole:
> - 'areashop message %clicker% %lang:confirm-sell|--region %region%|%'
> ```
> 
> this is how it works, but also prints "--region" in the message in the chat

i dont think you need `--region` here for the message command, the `--region` mostly applies to command like `as buy`

**Comment by seema84** [comment] 2024-11-26 18:21
shiftRightClickConsole:
- 'areashop message %clicker% %lang:confirm-sell|%region%|%'

so you can't click on it in the chat

**Comment by md5sha256** [comment] 2024-11-26 18:23
Ah, then yeah, i guess this breaks the rich text. The old format will be changed to use MiniMessage in the future, there are no plans to fix that specific behaviour until then. Feel free to make another issue for this.

**Comment by nuttapillar** [comment] 2024-11-29 14:46
![image](https://github.com/user-attachments/assets/c415a078-fc99-4f4c-8c6b-a4af2d3ae936)
So is this not correct?

**Comment by md5sha256** [comment] 2024-11-29 16:02
This is not correct. It should be `areashop rent --region %region%`

**Comment by nuttapillar** [comment] 2024-11-30 01:54
I set it to this, reloaded, and I still cant rent via the sign 
![image](https://github.com/user-attachments/assets/5e9ca451-6155-4d11-bd1d-3a7c0ecc76a0)

Is this the sorta thing that needs a full server reboot?
